linters-settings:
  goimports:
    local-prefixes: go.infratographer.com/x
  gofumpt:
    extra-rules: true

linters:
  enable:
    # default linters
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused


    # additional linters
    - bodyclose
    - gocritic
    - gocyclo
    - goerr113
    - gofmt
    # - gofumpt
    - goimports
    - gomnd
    - govet
    - misspell
    - noctx
    - revive
    - stylecheck
    - whitespace
    - wsl

    # - bod
issues:
  include:
    - EXC0001
    - EXC0002
    - EXC0003
    - EXC0004
    - EXC0005
    - EXC0006
    - EXC0007
    - EXC0008
    - EXC0009
    - EXC0010
    - EXC0011
    - EXC0012
    - EXC0013
    - EXC0014
    - EXC0015
