# yaml-language-server: $schema=https://golangci-lint.run/jsonschema/golangci.jsonschema.json

version: "2"
linters:
  enable:
    # Default
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused

    # Additional
    - bodyclose
    - gocritic
    - gocyclo
    - misspell
    - mnd
    - noctx
    - revive
    - whitespace
    - wsl
  exclusions:
    generated: lax
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    gofumpt:
      extra-rules: true
    goimports:
      local-prefixes:
        - go.infratographer.com/x
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
